name: .NET DLL Build & Release

on:
  push:
    branches: [ "feat/workflows_build"]
  pull_request:
    branches: [ "feat/workflows_build"]

env:
  SOLUTION_FILE: ProofAcidFireCold.sln
  PROJECT_PATH: ProofAcidFireCold.csproj
  DOTNET_VERSION: '4.6.2'
  BUILD_CONFIGURATION: Release

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}
      
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.nuget/packages
          **/bin
          **/obj
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Run tests
      run: dotnet test ${{ env.SOLUTION_FILE }} --configuration ${{ matrix.configuration }} --no-build --verbosity normal

    - name: Pack artifacts
      if: matrix.configuration == env.BUILD_CONFIGURATION
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration ${{ matrix.configuration }} --no-build --output ./artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dll-package-${{ matrix.configuration }}
        path: ./artifacts
        if-no-files-found: error