name: .NET DLL Build & Release

on:
  push:
    branches: [ "feat/workflows_build"]
  pull_request:
    branches: [ "feat/workflows_build"]

env:
  SOLUTION_FILE: ProofAcidFireCold.sln
  PROJECT_PATH: ProofAcidFireCold.csproj
  DOTNET_VERSION: '4.6.2'
  BUILD_CONFIGURATION: Release

jobs:
  build-and-pack:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # - name: Setup nuget
    #   uses: NuGet/setup-nuget@v2
    #   with:
    #     nuget-version: 5.x

    # # - name: Restore dependencies
    # #   run: nuget restore ${{ env.SOLUTION_FILE }}

    - name: Build solution
      run: msbuild ${{ env.SOLUTION_FILE }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform="Any CPU" /p:TargetFrameworkVersion=v${{ env.DOTNET_VERSION }}

    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProofAcidFireCold