name: .NET DLL Build & Release

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: ProofAcidFireCold
  SOLUTION_FILE: ProofAcidFireCold.sln
  PROJECT_PATH: ProofAcidFireCold.csproj
  DOTNET_VERSION: "8.0.x"
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.xml
        id: version
        run: |
          echo "version=$(grep -o '<version>[^<]*' package.xml | sed 's/<version>//')" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build solution
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Publish Artifact
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --output ./publish --no-build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{ steps.version.outputs.version }}
          path: ./publish/

  release:
    needs: build-and-pack
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        id: download
        with:
          name: ${{ env.PROJECT_NAME }}-${{ needs.build-and-pack.outputs.version }}
          path: "${{ env.PROJECT_NAME }}-${{ needs.build-and-pack.outputs.version }}"

      - name: zip Artifact and SHA256 hash
        id: ziphash
        run: |
          zip -r "${{ env.PROJECT_NAME }}-${{ needs.build-and-pack.outputs.version }}.zip" "${{ env.PROJECT_NAME }}-${{ needs.build-and-pack.outputs.version }}"
          echo "sha256=$(sha256sum ${{ env.PROJECT_NAME }}-${{ needs.build-and-pack.outputs.version }}.zip | awk '{ print $1 }')" >> $GITHUB_OUTPUT

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.PROJECT_NAME }}-${{ needs.build-and-pack.outputs.version }}.zip
          tag_name: ${{ needs.build-and-pack.outputs.version }}
          name: ${{ needs.build-and-pack.outputs.version }}
          body: |
            ## sha256
            - ${{ env.PROJECT_NAME }}-${{ needs.build-and-pack.outputs.version }}.zip: ${{ steps.ziphash.outputs.sha256 }}
          draft: true
          prerelease: true
